package dev.l2j.tesla.gameserver.enums;

public enum FailReason
{
	NO_TEXT,
	SYSTEM_ERROR_LOGIN_LATER,
	PASSWORD_DOES_NOT_MATCH_THIS_ACCOUNT,
	PASSWORD_DOES_NOT_MATCH_THIS_ACCOUNT2,
	ACCESS_FAILED_TRY_LATER,
	INCORRECT_ACCOUNT_INFO_CONTACT_CUSTOMER_SUPPORT,
	ACCESS_FAILED_TRY_LATER2,
	ACOUNT_ALREADY_IN_USE,
	ACCESS_FAILED_TRY_LATER3,
	ACCESS_FAILED_TRY_LATER4,
	ACCESS_FAILED_TRY_LATER5
}